namespace AwsMeetupGroup.DataServices.Infrastructure { 
   public static class AnalyticsSqlQueries {
       public readonly static string temperatureQuery = @"
        CREATE OR REPLACE STREAM ""TEMPERATURE_ANALYTICS_TOPIC"" (SITE_ID VARCHAR(1024), SENSOR_READING_VALUE VARCHAR(1024), READING_TIMESTAMP VARCHAR(1024), OUTSIDE_TEMPERATURE VARCHAR(1024));
        CREATE OR REPLACE PUMP ""STREAM_PUMP_TEMPERATURE"" AS INSERT INTO ""TEMPERATURE_ANALYTICS_TOPIC""
        SELECT STREAM s.SITE_ID as ""SITE_ID"", s.SENSOR_READING_VALUE as ""SENSOR_READING_VALUE"", s.READING_TIMESTAMP as ""READING_TIMESTAMP"", t.OUTSIDE_TEMPERATURE as ""OUTSIDE_TEMPERATURE""
        FROM ""temperature_001"" s LEFT JOIN ""TEMPERATURE_REFERENCE_TABLE"" t
        ON s.SITE_ID=t.SITE_ID
        WHERE s.SENSOR_TYPE='TEMPERATURE';
       ";
       public readonly static string pressureQuery = @"
        CREATE OR REPLACE STREAM ""PRESSURE_ANALYTICS_TOPIC"" (SITE_ID VARCHAR(1024), SENSOR_READING_VALUE VARCHAR(1024), READING_TIMESTAMP VARCHAR(1024), ALTITUDE VARCHAR(1024));
        CREATE OR REPLACE PUMP ""STREAM_PUMP_PRESSURE"" AS INSERT INTO ""PRESSURE_ANALYTICS_TOPIC""
        SELECT STREAM s.SITE_ID as ""SITE_ID"", s.SENSOR_READING_VALUE as ""SENSOR_READING_VALUE"", s.READING_TIMESTAMP as ""READING_TIMESTAMP"", t.ALTITUDE as ""ALTITUDE""
        FROM ""pressure_001"" s LEFT JOIN ""PRESSURE_REFERENCE_TABLE"" t
        ON s.SITE_ID=t.SITE_ID
        WHERE s.SENSOR_TYPE='PRESSURE';
       ";
   }
}


// SITE_ID string,
// SENSOR_READING_VALUE string,
// READING_TIMESTAMP string,
// OUTSIDE_TEMPERATURE string 